name: instaclone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.2
  eva_icons_flutter: ^3.1.0
  firebase_core: ^1.21.0
  firebase_auth: ^3.6.4
  cloud_firestore: ^3.4.9
  firebase_storage: ^10.3.9
  platform_device_id: ^1.0.1
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  shared_preferences: ^2.0.15
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

